/** Editorial draft. Confirm the current operator in /legal before publishing. */
export const TERMS_UPDATED_AT = '2026-09-10'
export const TERMS_CONTACT = 'gorandomfun@gmail.com'
type Terms = { title: string; intro: string; updated: string; editor: string; privacy: string; home: string; sections: { title: string; body: string }[] }
export const termsCopy: Record<'en' | 'fr' | 'de' | 'es' | 'jp', Terms> = {
  fr: {
    title: 'Conditions générales d’utilisation', updated: 'Dernière mise à jour', editor: 'Mentions légales et éditeur', privacy: 'Confidentialité', home: 'Retour à Random',
    intro: 'Ces conditions décrivent l’utilisation de Random, accessible sur gorandom.fun. L’identité et les coordonnées de l’éditeur figurent dans les mentions légales. La politique de confidentialité décrit séparément les traitements de données.',
    sections: [
      { title: '1. Le service', body: 'Random est un service gratuit de découverte de vidéos, images, liens, textes et quiz. Il propose des contenus sélectionnés dans un catalogue, avec une part d’aléatoire. Il ne garantit ni l’exhaustivité des sources ni la pertinence de chaque découverte pour chaque personne.' },
      { title: '2. Contenus et services tiers', body: 'De nombreux contenus sont hébergés et diffusés par des tiers, notamment YouTube et Dailymotion. Leur disponibilité, leurs restrictions d’âge ou de territoire et le fonctionnement de leurs lecteurs dépendent aussi de ces services. Leurs conditions s’appliquent à leur utilisation. Random peut retirer un lien ou un contenu indisponible ou signalé, notamment pour respecter la loi ou les droits de tiers.' },
      { title: '3. Cookies, vidéos et publicité', body: 'Les autorisations relatives aux lecteurs optionnels et à A-ADS sont séparées. Un refus peut rendre certaines vidéos indisponibles ; il ne constitue pas une acceptation d’autres traceurs. Certains lecteurs peuvent rester accessibles avec uniquement les traceurs nécessaires à leur fonctionnement. Les acceptations, y compris partielles, sont mémorisées 180 jours si le navigateur le permet. Un refus total est conservé pour la visite et le choix est reproposé lors d’une nouvelle visite. Les réglages de confidentialité permettent de modifier les choix. Les présentes conditions ne valent pas consentement aux cookies. Les publicités intégrées aux lecteurs tiers sont distinctes des annonces A-ADS de Random.' },
      { title: '4. Propriété intellectuelle', body: 'Les droits sur les contenus restent ceux de leurs titulaires. L’affichage d’un contenu ou son ajout aux favoris ne donne aucun droit de reproduction, de téléchargement ou de réutilisation au-delà des autorisations du titulaire et de la loi. Les éléments propres à Random sont également protégés lorsqu’ils remplissent les conditions légales de protection.' },
      { title: '5. Usage du service', body: 'L’utilisateur doit respecter la loi, les droits des tiers et les restrictions applicables aux contenus. Il ne doit pas tenter d’accéder sans autorisation aux systèmes, perturber le service, contourner ses protections ou utiliser ses fonctions pour des activités illicites. La diversité des contenus appelle une vigilance adaptée à l’âge des utilisateurs. Les restrictions des plateformes doivent être respectées.' },
      { title: '6. Favoris et disponibilité', body: 'Certains favoris et préférences sont conservés dans le navigateur. Ils peuvent être perdus si ces données sont effacées ou si le navigateur ou l’appareil change. Un contenu tiers peut disparaître même s’il figure dans des favoris. Random peut connaître des interruptions liées à la maintenance, à des incidents ou à ses fournisseurs. Les textes et quiz peuvent contenir des erreurs ; ils ne remplacent pas un conseil professionnel adapté.' },
      { title: '7. Signalements et contact', body: 'Pour signaler un contenu illicite, une atteinte à un droit ou un problème technique, écrivez à gorandomfun@gmail.com en précisant le lien du contenu, le motif du signalement et les éléments utiles à son examen. Les signalements sont examinés et peuvent conduire notamment au retrait du référencement du contenu sur Random. Ce retrait ne supprime pas le contenu chez son hébergeur.' },
      { title: '8. Droits et évolution des conditions', body: 'Aucune disposition de ces conditions n’écarte les droits impératifs de l’utilisateur, notamment les protections des consommateurs applicables à sa situation, ni les responsabilités que la loi impose à l’éditeur. Les conditions peuvent évoluer avec le service ; la version publiée porte sa date de mise à jour. Les changements nécessitant une information particulière ou un nouvel accord sont traités conformément aux règles applicables.' },
    ],
  },
  en: {
    title: 'Terms of use', updated: 'Last updated', editor: 'Legal notice and operator', privacy: 'Privacy', home: 'Back to Random',
    intro: 'These terms describe the use of Random at gorandom.fun. The operator’s identity and contact details are provided in the legal notice. The privacy policy separately explains the processing of personal data.',
    sections: [
      { title: '1. The service', body: 'Random is a free discovery service for videos, images, links, texts and quizzes. It selects content from a catalogue with an element of randomness. It does not guarantee exhaustive coverage or that every discovery will appeal to every person.' },
      { title: '2. Third-party content and services', body: 'Much of the content is hosted and delivered by third parties, including YouTube and Dailymotion. Availability, age and territorial restrictions, and player operation also depend on those services. Their terms apply to their use. Random may remove links to unavailable or reported content, including to comply with the law or third-party rights.' },
      { title: '3. Cookies, videos and advertising', body: 'Acceptances, including partial choices, are saved for 180 days when browser storage is available. A full refusal is kept for this visit; we ask again on a new visit. You can change your choice in Privacy settings. Permissions for optional players and A-ADS are separate. Refusing permission may make some videos unavailable; it does not authorise other trackers. Some players may remain available using only storage necessary for their operation. Choices can be changed through Privacy settings. These terms do not constitute cookie consent. Ads inside third-party players are separate from Random’s A-ADS advertisements.' },
      { title: '4. Intellectual property', body: 'Content rights remain with their respective holders. Displaying or saving content as a favourite does not grant rights to reproduce, download or reuse it beyond what the right holder and the law permit. Random’s own materials are also protected where they meet the legal requirements for protection.' },
      { title: '5. Use of the service', body: 'Users must comply with the law, third-party rights and content restrictions. They must not access systems without authorisation, disrupt the service, bypass its safeguards or use its features for unlawful activities. The variety of content requires care appropriate to the user’s age. Platform restrictions must be respected.' },
      { title: '6. Favourites and availability', body: 'Some favourites and preferences are stored in the browser. They may be lost when browser data is cleared or the browser or device changes. Third-party content may disappear even if saved as a favourite. Maintenance, incidents or supplier issues may interrupt Random. Texts and quizzes may contain errors and do not replace appropriate professional advice.' },
      { title: '7. Reporting and contact', body: 'To report unlawful content, a rights infringement or a technical issue, write to gorandomfun@gmail.com with the content link, the reason for the report and useful supporting details. Reports are reviewed and may lead to removal of the content’s listing on Random. Removing a listing does not remove the content from its host.' },
      { title: '8. Rights and changes', body: 'These terms do not exclude mandatory user rights, including consumer protections applicable to the user’s circumstances, or liabilities imposed on the operator by law. The terms may evolve with the service; the published version shows its update date. Changes requiring specific notice or renewed agreement are handled under the applicable rules.' },
    ],
  },
  de: {
    title: 'Nutzungsbedingungen', updated: 'Zuletzt aktualisiert', editor: 'Impressum und Betreiber', privacy: 'Datenschutz', home: 'Zurück zu Random',
    intro: 'Diese Bedingungen beschreiben die Nutzung von Random auf gorandom.fun. Identität und Kontaktdaten des Betreibers stehen im Impressum. Die Datenschutzerklärung erläutert die Verarbeitung personenbezogener Daten gesondert.',
    sections: [
      { title: '1. Der Dienst', body: 'Random ist ein kostenloser Entdeckungsdienst für Videos, Bilder, Links, Texte und Quizfragen. Inhalte werden mit einem Zufallsanteil aus einem Katalog ausgewählt. Eine vollständige Abdeckung der Quellen oder die persönliche Relevanz jeder Entdeckung wird nicht garantiert.' },
      { title: '2. Inhalte und Dienste Dritter', body: 'Viele Inhalte werden von Dritten gehostet und bereitgestellt, etwa YouTube und Dailymotion. Verfügbarkeit, Alters- und Gebietsbeschränkungen sowie die Funktion der Player hängen auch von diesen Diensten ab. Für ihre Nutzung gelten deren Bedingungen. Random kann Verweise auf nicht verfügbare oder gemeldete Inhalte entfernen, insbesondere zur Einhaltung von Gesetzen oder Rechten Dritter.' },
      { title: '3. Cookies, Videos und Werbung', body: 'Zustimmungen, auch teilweise, werden 180 Tage gespeichert, sofern der Browser dies erlaubt. Eine vollständige Ablehnung gilt für diesen Besuch; bei einem neuen Besuch fragen wir erneut. Die Auswahl lässt sich in den Datenschutzeinstellungen ändern. Die Erlaubnisse für optionale Player und A-ADS sind getrennt. Eine Ablehnung kann einzelne Videos unzugänglich machen und erlaubt keine anderen Tracker. Manche Player bleiben mit ausschließlich notwendigem Speicher verfügbar. Die Auswahl lässt sich in den Datenschutzeinstellungen ändern. Diese Bedingungen stellen keine Cookie-Einwilligung dar. Werbung in Playern Dritter ist von der A-ADS-Werbung auf Random zu unterscheiden.' },
      { title: '4. Geistiges Eigentum', body: 'Die Rechte an Inhalten verbleiben bei den jeweiligen Rechteinhabern. Das Anzeigen oder Speichern als Favorit gewährt keine darüber hinausgehenden Rechte zur Vervielfältigung, zum Herunterladen oder zur Weiterverwendung. Maßgeblich sind die Erlaubnisse des Rechteinhabers und das Gesetz. Eigene Inhalte von Random sind geschützt, soweit sie die gesetzlichen Schutzvoraussetzungen erfüllen.' },
      { title: '5. Nutzung des Dienstes', body: 'Nutzer müssen Gesetze, Rechte Dritter und Inhaltsbeschränkungen beachten. Unbefugter Systemzugriff, Störung des Dienstes, Umgehung von Schutzmaßnahmen und rechtswidrige Nutzung sind untersagt. Die Vielfalt der Inhalte erfordert altersgerechte Aufmerksamkeit. Plattformbeschränkungen sind einzuhalten.' },
      { title: '6. Favoriten und Verfügbarkeit', body: 'Einige Favoriten und Einstellungen werden im Browser gespeichert. Beim Löschen dieser Daten oder beim Wechsel des Browsers oder Geräts können sie verloren gehen. Inhalte Dritter können auch dann verschwinden, wenn sie als Favorit gespeichert sind. Wartung, Störungen oder Lieferantenprobleme können Random unterbrechen. Texte und Quizfragen können Fehler enthalten und ersetzen keine geeignete professionelle Beratung.' },
      { title: '7. Meldungen und Kontakt', body: 'Rechtswidrige Inhalte, Rechtsverletzungen oder technische Probleme können an gorandomfun@gmail.com gemeldet werden. Bitte Inhaltslink, Grund und hilfreiche Angaben beifügen. Meldungen werden geprüft und können zur Entfernung des Verweises auf Random führen. Dadurch wird der Inhalt nicht bei seinem Hostinganbieter gelöscht.' },
      { title: '8. Rechte und Änderungen', body: 'Diese Bedingungen schließen weder zwingende Nutzerrechte, einschließlich anwendbarer Verbraucherschutzrechte, noch gesetzlich vorgeschriebene Haftung des Betreibers aus. Die Bedingungen können sich mit dem Dienst ändern; die veröffentlichte Fassung enthält das Aktualisierungsdatum. Änderungen, die eine besondere Mitteilung oder erneute Zustimmung erfordern, werden nach den anwendbaren Regeln behandelt.' },
    ],
  },
  es: {
    title: 'Condiciones de uso', updated: 'Última actualización', editor: 'Aviso legal y responsable', privacy: 'Privacidad', home: 'Volver a Random',
    intro: 'Estas condiciones describen el uso de Random en gorandom.fun. La identidad y los datos de contacto del responsable figuran en el aviso legal. La política de privacidad explica por separado el tratamiento de datos personales.',
    sections: [
      { title: '1. El servicio', body: 'Random es un servicio gratuito para descubrir vídeos, imágenes, enlaces, textos y cuestionarios. Selecciona contenidos de un catálogo con un componente aleatorio. No garantiza una cobertura exhaustiva de las fuentes ni que cada descubrimiento interese a todas las personas.' },
      { title: '2. Contenidos y servicios de terceros', body: 'Muchos contenidos están alojados y se reproducen mediante terceros, como YouTube y Dailymotion. Su disponibilidad, restricciones de edad o territorio y funcionamiento también dependen de estos servicios. Sus condiciones se aplican a su uso. Random puede retirar enlaces a contenidos no disponibles o denunciados, en particular para cumplir la ley o respetar derechos de terceros.' },
      { title: '3. Cookies, vídeos y publicidad', body: 'Las aceptaciones, incluidas las parciales, se guardan durante 180 días si el navegador lo permite. El rechazo total se conserva durante esta visita; volveremos a preguntar en una nueva visita. Puedes cambiarlo en los ajustes de privacidad. Los permisos para reproductores opcionales y A-ADS son independientes. Rechazar un permiso puede impedir ver algunos vídeos, pero no autoriza otros rastreadores. Algunos reproductores pueden seguir disponibles con almacenamiento exclusivamente necesario. Las preferencias se modifican en los ajustes de privacidad. Estas condiciones no constituyen consentimiento para cookies. Los anuncios dentro de reproductores externos son distintos de los anuncios A-ADS de Random.' },
      { title: '4. Propiedad intelectual', body: 'Los derechos sobre los contenidos siguen perteneciendo a sus titulares. Mostrar un contenido o guardarlo como favorito no otorga derechos de reproducción, descarga o reutilización más allá de lo autorizado por el titular y la ley. Los elementos propios de Random también están protegidos cuando cumplen los requisitos legales.' },
      { title: '5. Uso del servicio', body: 'Los usuarios deben respetar la ley, los derechos de terceros y las restricciones de los contenidos. No deben acceder a sistemas sin autorización, perturbar el servicio, eludir sus protecciones ni utilizarlo para actividades ilícitas. La variedad de los contenidos requiere una atención adecuada a la edad. Deben respetarse las restricciones de las plataformas.' },
      { title: '6. Favoritos y disponibilidad', body: 'Algunos favoritos y preferencias se guardan en el navegador y pueden perderse al borrar los datos o cambiar de navegador o dispositivo. Un contenido de terceros puede desaparecer aunque esté guardado. El mantenimiento, los incidentes o los problemas de proveedores pueden interrumpir Random. Los textos y cuestionarios pueden contener errores y no sustituyen el asesoramiento profesional adecuado.' },
      { title: '7. Avisos y contacto', body: 'Para comunicar contenidos ilícitos, infracciones de derechos o problemas técnicos, escribe a gorandomfun@gmail.com con el enlace, el motivo y los datos útiles para su examen. Los avisos se revisan y pueden dar lugar a la retirada del enlace en Random. Esto no elimina el contenido de su proveedor de alojamiento.' },
      { title: '8. Derechos y cambios', body: 'Estas condiciones no excluyen los derechos imperativos del usuario, incluidas las protecciones aplicables a consumidores, ni las responsabilidades que la ley impone al responsable del servicio. Pueden evolucionar con el servicio; la versión publicada indica su fecha de actualización. Los cambios que requieran información específica o un nuevo acuerdo se gestionan conforme a las normas aplicables.' },
    ],
  },
  jp: {
    title: '利用規約', updated: '最終更新日', editor: '運営者情報・法的表示', privacy: 'プライバシー', home: 'Randomに戻る',
    intro: '本規約はgorandom.funで提供するRandomの利用について説明します。運営者の氏名または名称と連絡先は法的表示に記載します。個人データの取り扱いはプライバシーポリシーで別途説明します。',
    sections: [
      { title: '1. サービス', body: 'Randomは動画、画像、リンク、文章、クイズを発見するための無料サービスです。カタログから、ランダムな要素を含む方法でコンテンツを選びます。情報源の網羅性や、すべての発見がすべての利用者の好みに合うことは保証しません。' },
      { title: '2. 外部コンテンツとサービス', body: '多くのコンテンツはYouTubeやDailymotionなどの第三者が保存・配信しています。視聴可否、年齢・地域制限、プレーヤーの動作は各サービスにも依存し、その利用には各社の規約が適用されます。Randomは、法律や第三者の権利を守るためなどに、利用できないコンテンツや通報されたコンテンツへのリンクを削除する場合があります。' },
      { title: '3. Cookie、動画、広告', body: '一部のみの許可を含め、許可の選択はブラウザーで保存できる場合に180日間記憶されます。すべて拒否した場合は今回の訪問中のみ記憶し、新たな訪問時に再び選択を表示します。プライバシー設定でいつでも変更できます。 任意のプレーヤーとA-ADSの許可は別々です。拒否すると一部の動画を視聴できなくなる場合がありますが、他のトラッカーが許可されることはありません。動作に必要な保存データのみを使用するプレーヤーは利用できる場合があります。選択はプライバシー設定で変更できます。本規約への同意はCookieへの同意にはなりません。外部プレーヤー内の広告とRandomのA-ADS広告は別です。' },
      { title: '4. 知的財産', body: 'コンテンツの権利は各権利者に帰属します。表示やお気に入りへの保存によって、権利者や法律が認める範囲を超える複製、ダウンロード、再利用の権利が与えられることはありません。Random独自の要素も、法的な保護要件を満たす場合には保護されます。' },
      { title: '5. 利用上のルール', body: '利用者は法律、第三者の権利、コンテンツの制限を守ってください。不正なシステムへのアクセス、サービス妨害、保護機能の回避、違法な目的での利用は禁止します。多様なコンテンツが含まれるため、年齢に応じた配慮が必要です。各プラットフォームの制限を守ってください。' },
      { title: '6. お気に入りと可用性', body: '一部のお気に入りや設定はブラウザーに保存されます。データの削除やブラウザー・端末の変更で失われる場合があります。お気に入りに保存していても外部コンテンツが削除される場合があります。保守、障害、外部事業者の問題によりRandomが中断することがあります。文章やクイズには誤りが含まれる場合があり、適切な専門家の助言に代わるものではありません。' },
      { title: '7. 通報とお問い合わせ', body: '違法なコンテンツ、権利侵害、技術的な問題はgorandomfun@gmail.comまでご連絡ください。対象リンク、理由、確認に役立つ情報を添えてください。通報を確認し、Random上のリンクを削除するなどの対応を行う場合があります。リンクの削除は配信元のコンテンツ自体の削除を意味しません。' },
      { title: '8. 権利と規約の変更', body: '本規約は、利用者に適用される消費者保護などの強行法規上の権利や、法律が運営者に課す責任を排除しません。サービスの変更に伴い規約を改定する場合があり、公表版には更新日を記載します。特別な通知や改めての同意が必要な変更は、適用される規則に従って取り扱います。' },
    ],
  },
}
