const enDictionary = {
  "hero": {
    "tagline1": "EXPLORE RANDOM CONTENTS.",
    "tagline2": "NO MISSION, NO GOAL, NO REASON.",
    "tagline3": "ONLY USELESS SURPRISE.",
    "startButton": "GO RANDOM",
    "noroscopeButton": "6 RANDOM"
  },
  "noroscope": {
    "menu": "6 RANDOM",
    "titleBar": "Your 6 RANDOM",
    "shareTitle": "Share your 6 RANDOM",
    "shareAction": "Share this 6 RANDOM",
    "loading": "Aligning today's 6 RANDOM...",
    "error": "Couldn't load everything. Give it another try.",
    "retry": "Try again",
    "empty": "No content available yet.",
    "expressionFallback": "The vibes are undecided today.",
    "tiles": {
      "weirdDrop": "1. Weird Drop",
      "luckyMess": "2. Lucky Mess",
      "dumbSpark": "3. Dumb Spark",
      "randomVibe": "4. Random Vibe",
      "lostThought": "5. Lost Thought",
      "secretUselessness": "6. Secret Uselessness"
    },
    "instructions": "Tap the squares and uncover your vibe of the day.",
    "progress": {
      "none": "Nothing revealed yet. Pick a square to start.",
      "partial": "{count}/{total} vibes revealed. Keep going.",
      "full": ""
    },
    "revealAction": "Reveal this vibe",
    "revealUnavailable": "Content still loading",
    "tileFallback": "Reveal me",
    "aiDisclaimer": "Generated by AI – {source}"
  },
  "nav": {
    "images": "images",
    "videos": "videos",
    "web": "web",
    "quotes": "quotes",
    "jokes": "funny jokes",
    "facts": "facts"
  },
  "footer": {
    "social": "social",
    "legal": "Legal notice.",
    "share": "share"
  },
  "modal": {
    "randomAgain": "Random again",
    "like": "Like",
    "dislike": "Dislike",
    "share": "Share"
  },
  "likes": {
    "title": "Your Likes",
    "empty": "No likes yet",
    "maxReached": "Maximum 6 likes reached!",
    "keep24h": "Stored locally on this device.",
    "youTab": "YOU",
    "weTab": "WE",
    "youDescription": "Your",
    "youSuffix": "stay on this device.",
    "weDescription": "Here is the most",
    "weSuffix": "content.",
    "banner": {
      "youPrefix": "Your",
      "youSuffix": "stay on this device.",
      "wePrefix": "Here is the most",
      "weSuffix": "content."
    },
    "weEmpty": "No global favourites yet. Be the first to like something!"
  },
  "shareMenu": {
    "siteName": "Random",
    "title": "Share",
    "close": "Close",
    "native": "Share by message",
    "copy": "Copy",
    "copied": "Copied!",
    "itemsLabel": "Shared items"
  },
  "video": {
    "fullscreen": "Fullscreen",
    "openExternally": "Open in app"
  },
  "shuffle": {
    "title": "Filter content",
    "all": "Everything",
    "imagesVideos": "Images & Videos",
    "imagesOnly": "Images only"
  },
  "minigames": {
    "card": {
      "unavailable": "Mini-game currently unavailable.",
      "category": "Mini-game",
      "level": "Level {level}",
      "rulesIntro": "Ready? Here are the rules:",
      "defaultRule": "Have fun and stay focused.",
      "actions": {
        "start": "Start",
        "replay": "Replay",
        "guide": "Guide"
      },
      "result": {
        "win": "Victory!",
        "lose": "Defeat"
      }
    },
    "games": {
      "tap-to-not-tap": {
        "name": "Tap-to-not-Tap",
        "tagline": "Follow the rhythm without messing up.",
        "instructions": [
          "TAP / DON'T TAP flashes are separated by real blanks.",
          "Click only during TAP, stay still during DON'T TAP.",
          "At level 1–2 you only have 2 mistakes."
        ],
        "status": {
          "ready": "Sequence starting...",
          "tap": "TAP! Click before the next flash.",
          "dontTap": "DON'T TAP!",
          "tip": "Click only when the word TAP shows up. Each flash gets faster.",
          "encourage": "Nice timing! Stay focused.",
          "errorCount": "{reason} · error {current}/{max}"
        },
        "messages": {
          "missedTap": "You missed a TAP.",
          "wrongClick": "You shouldn't have clicked.",
          "sequenceComplete": "Sequence complete!",
          "sequenceInterrupted": "Sequence interrupted.",
          "tooManyErrors": "Too many mistakes!"
        },
        "details": {
          "steps": "Steps",
          "success": "Successful TAPs",
          "errors": "Errors"
        },
        "hud": {
          "step": "Step",
          "tapCount": "TAP hits",
          "errors": "Errors"
        }
      },
      "emoji-echo": {
        "name": "Emoji Echo",
        "tagline": "Remember the sequence.",
        "instructions": [
          "Two sequences per level: e.g., 2 then 3 emojis.",
          "Each sequence replays from scratch with new emojis.",
          "Repeat them perfectly before the timer ends."
        ],
        "status": {
          "observeSequence": "Watch the emoji sequence...",
          "observe": "Watch...",
          "repeat": "Repeat the sequence!"
        },
        "messages": {
          "timeout": "Too slow.",
          "wrong": "That wasn't the right order!",
          "perfect": "Perfect memory!"
        },
        "details": {
          "sequence": "Sequence reached"
        },
        "hud": {
          "progress": "Sequence {current}/{total} · Length {length}"
        }
      },
      "useless-progress-bar": {
        "name": "Useless Progress Bar",
        "tagline": "A bar that never ends... almost.",
        "instructions": [
          "Hold the button to charge the bar continuously.",
          "Release exactly on the target (± tolerance).",
          "Every overshoot ends the run instantly."
        ],
        "status": {
          "ready": "Charge the useless bar precisely...",
          "target": "Goal {current}/{total} · Aim for {target}% (±{tolerance}%)"
        },
        "messages": {
          "timeout": "Time is up!",
          "over": "Overcharged!",
          "under": "Not enough charge!",
          "win": "Perfectly calibrated useless bar!"
        },
        "details": {
          "validated": "Targets cleared",
          "lastGoal": "Last goal"
        },
        "hud": {
          "progress": "Charge {progress}% · Target {target}% ± {tolerance}%",
          "timer": "Time: {seconds}s · Target {current}/{total}"
        },
        "buttons": {
          "press": "Hold to charge",
          "release": "Release to validate"
        }
      },
      "left-or-right": {
        "name": "Left or Right?",
        "tagline": "Pick the arrow that appears less.",
        "instructions": [
          "Watch the recent arrows (5 to 9 depending on level).",
          "Choose the one that appears the least.",
          "Limit consecutive mistakes."
        ],
        "details": {
          "rounds": "Rounds",
          "success": "Successes",
          "errors": "Errors"
        },
        "status": {
          "intro": "Choose the least frequent arrow in the last {count}!",
          "analyzing": "Analyzing...",
          "tie": "Perfect tie: pick any.",
          "guidance": "{direction} is the rarest (diff {diff}).",
          "correct": "Nice call! Keep going.",
          "mistake": "Oops, that wasn't the best option..."
        },
        "messages": {
          "tooMany": "Too many mistakes.",
          "success": "Challenge complete!",
          "fail": "One mistake too many.",
          "time": "Time is up."
        },
        "feedback": {
          "correct": "Nice call!",
          "wrong": "Try the other direction."
        },
        "directions": {
          "left": "← Left",
          "right": "Right →",
          "either": "← or →"
        },
        "hud": {
          "history": "Last {count}: ← {left} · → {right}",
          "target": "Target: {label}",
          "round": "Round {round}/{total} · Successes {successes} · Errors {mistakes}/{allowed} · Time {seconds}s"
        }
      },
      "fake-loading-race": {
        "name": "Loading Race",
        "tagline": "Bet on the winning loader.",
        "instructions": [
          "Pick your loader (3 to 5 bars) before the start.",
          "You can swap your bet once mid-race.",
          "Watch speed changes and guess the winner."
        ],
        "messages": {
          "start": "Bet on the winning loader!",
          "selected": "You bet on loader {index}. Race launched!",
          "swap": "You switch to loader {index}!",
          "win": "Your loader {index} crosses the line first!",
          "lose": "Loader {index} wins the race.",
          "hint": "You can switch bets only once during the race."
        },
        "details": {
          "bet": "Bet",
          "none": "None",
          "winner": "Winner"
        },
        "labels": {
          "loader": "Loader {index}"
        },
        "buttons": {
          "bet": "Bet",
          "switch": "Switch",
          "locked": "Bet",
          "replay": "Replay",
          "exit": "Exit"
        },
        "finish": {
          "prefix": "Finish:",
          "entry": "{position} → Loader {runner}"
        },
        "result": {
          "winTitle": "Victory!",
          "loseTitle": "Defeat",
          "summary": "Bet: {bet} · Winner: Loader {winner}"
        }
      },
      "color-off-by-one": {
        "name": "Color Off-By-One",
        "tagline": "A barely different shade.",
        "instructions": [
          "Study the grid (3×3 growing to 5×5).",
          "Click the slightly different tile.",
          "Higher levels make the hues almost identical."
        ],
        "details": {
          "round": "Round",
          "difference": "Difference"
        },
        "status": {
          "look": "Spot the different shade.",
          "harder": "Even subtler..."
        },
        "messages": {
          "win": "Eagle eyes!",
          "fail": "That wasn't the odd shade."
        },
        "hud": {
          "round": "Round {round}/{total}"
        },
        "aria": {
          "tile": "Tile {index}"
        }
      },
      "steady-spots": {
        "name": "Steady Spots",
        "tagline": "Land on every glow without shaking.",
        "instructions": [
          "Reach each halo in the requested order.",
          "Hold your pointer on it ~2 s without moving.",
          "Advanced levels add spots and shrink their size."
        ],
        "status": {
          "start": "Reach each spot and hold about 2 seconds.",
          "validated": "Spot cleared!",
          "next": "Spot {next}/{total} — click and hold 2 s.",
          "hold": "Don't move...",
          "win": "You held every spot!"
        },
        "messages": {
          "time": "Time is up.",
          "leftSpot": "You left the spot!",
          "released": "You released too early.",
          "leftArea": "You left the area."
        },
        "details": {
          "validated": "Spots cleared"
        },
        "hud": {
          "progress": "Spot {current}/{total} · Time {seconds}s"
        },
        "overlay": {
          "hold": "Hold"
        }
      }
    }
  },
  "add": {
    "title": "Add",
    "banner": "Add the content you",
    "pendingNote": "Every submission is curated by humans. Thanks for your patience!",
    "tabs": {
      "image": "Image",
      "text": "Jokes · Quotes · Facts",
      "web": "Web",
      "video": "Videos"
    },
    "remainingSpace": "Remaining space:",
    "storageFull": "Submissions are full for now. Try again later.",
    "image": {
      "uploadLabel": "Drop or upload an image",
      "limit": "Max 1 MB. PNG, JPG, GIF accepted.",
      "select": "Choose a file",
      "urlLabel": "Or paste an image URL",
      "previewAlt": "Selected image preview",
      "remove": "Remove file",
      "firstName": "First name",
      "lastName": "Last name",
      "keywordsLabel": "Image keywords",
      "keywordsHint": "Add 4–5 keywords separated by commas (portrait, street, night...)"
    },
    "fileTooLarge": "The selected image is larger than 1 MB.",
    "errors": {
      "invalidImage": "Please choose an image file.",
      "imageRequired": "Please upload or link to an image.",
      "textRequired": "Share something before submitting.",
      "urlRequired": "Please share a valid URL.",
      "storageUnavailable": "Submissions are down right now. Please retry later.",
      "missingContributor": "Please tell us who captured this image.",
      "missingAuthor": "Please share who said this quote.",
      "duplicate": "We already have this link in our queue.",
      "missingKeywords": "Please add 4–5 keywords for your image."
    },
    "text": {
      "placeholder": "Write your best joke, quote or fact...",
      "options": {
        "joke": "Joke",
        "quote": "Quote",
        "fact": "Fact"
      },
      "authorLabel": "Who said it?",
      "authorPlaceholder": "Author"
    },
    "web": {
      "urlLabel": "Website URL"
    },
    "video": {
      "urlLabel": "Video URL",
      "disclaimer": "We host only links, not video files. Share a platform URL.",
      "embedWarning": "This link may not allow embedding. We will double-check manually."
    },
    "analyzing": "Analyzing...",
    "analyzeError": "Could not analyze this link yet. You can still submit it.",
    "email": {
      "label": "Your email (required)",
      "placeholder": "you@example.com",
      "required": "Email is required to submit."
    },
    "success": "Thanks! We will review your submission soon.",
    "error": "Unable to submit right now. Please try again.",
    "submitting": "Sending...",
    "submit": "Send content"
  },
  legal: {
    title: "Legal notice",
    subtitle: "Clarity on responsibility",
    close: "Close",
    disclaimer: {
      title: "Content advisory",
      body:
        "Random aggregates content from APIs and manual submissions. We cannot pre-screen every piece. If something looks unlawful or harmful, please capture it and email gorandomfun@gmail.com so we can remove it quickly.",
    },

    editor: {
      title: "Publisher",
      body:
        "RANDOM Studio (sole proprietorship) — SIREN 514 550 698 — SIRET 514 550 698 00013\n" +
        "NAF 7410Z — 17 Grand Rue, 67110 Gundershoffen, France — Contact: gorandomfun@gmail.com"
    },

    hosting: {
      title: "Hosting",
      body: "Vercel Inc., 440 N Barranca Ave #4133, Covina, CA 91723, USA — vercel.com"
    },

    purpose: {
      title: "Purpose",
      body: "Random content (images, GIFs, videos, text) for entertainment. Monetised with contextual ads (A-ADS) and occasional affiliate links."
    },

    privacy: {
      title: "Cookies & privacy",
      bodyPrefix: "We only set essential cookies (language choice, consent log). A-ADS delivers ads without tracking cookies; if we add other trackers they will appear here for opt-in.",
      manageCookies: "Manage my cookies",
      privacyPolicy: "Privacy policy"
    },

    usa: {
      title: "USA",
      bodyPrefix: "We do not sell or share personal data. To exercise CCPA/CPRA rights, email gorandomfun@gmail.com.",
      doNotSell: "Do Not Sell or Share"
    },

    dmca: {
      title: "DMCA",
      body: "DMCA notices: gorandomfun@gmail.com"
    },

    law: {
      title: "Governing law",
      body: "Governing law: France, unless mandatory local law applies."
    }
  }  ,
  "encourage": {
    "roundLabel": "Round",
    "messages": [
      "You pierced a brand-new layer.",
      "Another circuit of randomness cleared.",
      "Beyond the obvious—keep climbing.",
      "You just cracked a fresh portal.",
      "The mainstream fades behind you.",
      "Next tier of weird unlocked.",
      "You’re steering past the predictable.",
      "Fresh glitch signals ahead.",
      "Momentum is pulling you deeper.",
      "You jumped over the comfort line.",
      "Hidden corners light back up.",
      "The odd frontier salutes you.",
      "Curiosity just levelled up.",
      "Maps end, your trail continues.",
      "A new rabbit hole appears.",
      "Rare vibes gathered.",
      "The random engine roars louder.",
      "Off-road ideas unlocked.",
      "The unexpected trusts you now.",
      "Your explorer badge just glows brighter.",
      "Keep pushing; stranger wonders wait.",
      "You outran routine once again.",
      "Another cryptic chamber opens.",
      "Stay restless, the signal is forward."
    ]
  }

}

export default enDictionary
