const en = {
  title: 'Your Random experience',
  intro: 'Without permission for video players, your Random experience is limited: some videos remain blocked. Enable them to discover more content. A-ADS advertising helps support Random and remains a separate choice.',
  accept: 'Accept videos and advertising',
  reject: 'Reject optional services',
  settings: 'Privacy settings',
  close: 'Close',
  save: 'Save choices',
  necessary: 'Essential storage',
  necessaryText: 'Language, preferences, saved likes and your privacy choice.',
  media: 'Optional video players',
  mediaText: 'Allow YouTube and other players requiring permission. They receive connection data and may use cookies or similar technologies. This choice does not enable A-ADS.',
  standardMediaText: 'Standard Dailymotion videos may remain available with essential storage only. Dailymotion receives connection data and may show its own ads. Its player notices remain available.',
  ads: 'A-ADS advertising',
  adsText: 'Allow A-ADS advertising to support Random. This external service receives connection data. You can allow videos separately.',
  gpc: 'Your browser privacy signal is active: A-ADS advertising remains disabled.',
  blocked: 'A limited Random experience. Without permission for external players, some videos stay blocked. Enable them for a fuller experience.',
  allow: 'Allow videos only',
  both: 'Accept videos and advertising',
  customize: 'Personalize',
  remembered: 'Acceptances, including partial choices, are saved for 180 days when browser storage is available. A full refusal is kept for this visit; we ask again on a new visit. You can change your choice in Privacy settings.',
  limited: 'Video settings',
  shortcut: 'Privacy',
  terms: 'Terms of use',
  details: 'Data and privacy',
  policy: 'Privacy policy',
}

type Copy = typeof en

export const privacyCopy: Record<string, Copy> = {
  en,
  fr: {
    title: 'Votre expérience Random',
    intro: 'Sans autoriser les lecteurs vidéo, l’expérience Random est dégradée : certaines vidéos restent bloquées. Autorisez-les pour découvrir davantage de contenus. La publicité A-ADS aide à financer Random et reste un choix séparé.',
    accept: 'Accepter les vidéos et la publicité',
    reject: 'Refuser les services optionnels',
    settings: 'Réglages de confidentialité',
    close: 'Fermer',
    save: 'Enregistrer',
    necessary: 'Stockage nécessaire',
    necessaryText: 'Langue, préférences, favoris et choix de confidentialité.',
    media: 'Lecteurs vidéo optionnels',
    mediaText: 'Autoriser YouTube et les autres lecteurs soumis à votre accord. Ils reçoivent des données de connexion et peuvent utiliser des cookies ou technologies similaires. Ce choix n’active pas A-ADS.',
    standardMediaText: 'Les vidéos Dailymotion standard peuvent rester accessibles avec uniquement du stockage nécessaire. Dailymotion reçoit des données de connexion et peut diffuser ses propres publicités. Les informations de son lecteur restent accessibles.',
    ads: 'Publicité A-ADS',
    adsText: 'Autoriser les annonces A-ADS pour soutenir Random. Ce service externe reçoit des données de connexion. Les vidéos peuvent être autorisées séparément.',
    gpc: 'Le signal de confidentialité de votre navigateur est actif : la publicité A-ADS reste désactivée.',
    blocked: 'Une expérience Random dégradée. Sans autoriser les lecteurs externes, certaines vidéos restent bloquées. Activez-les pour une expérience plus complète.',
    allow: 'Autoriser seulement les vidéos',
    both: 'Accepter les vidéos et la publicité',
    customize: 'Personnaliser',
    remembered: 'Les acceptations, y compris partielles, sont mémorisées 180 jours si le navigateur le permet. Un refus total est conservé pour cette visite ; le choix sera reproposé lors d’une nouvelle visite. Vous pouvez le modifier dans les réglages de confidentialité.',
    limited: 'Réglages vidéo',
    shortcut: 'Confidentialité',
    terms: 'Conditions d’utilisation',
    details: 'Données et confidentialité',
    policy: 'Politique de confidentialité',
  },
  de: {
    title: 'Dein Random-Erlebnis',
    intro: 'Ohne die Erlaubnis für Videoplayer ist dein Random-Erlebnis eingeschränkt: Einige Videos bleiben gesperrt. Erlaube sie, um mehr Inhalte zu entdecken. A-ADS-Werbung hilft, Random zu finanzieren, und bleibt eine getrennte Entscheidung.',
    accept: 'Videos und Werbung erlauben',
    reject: 'Optionale Dienste ablehnen',
    settings: 'Datenschutzeinstellungen',
    close: 'Schließen',
    save: 'Speichern',
    necessary: 'Notwendiger Speicher',
    necessaryText: 'Sprache, Einstellungen, gespeicherte Likes und deine Datenschutzauswahl.',
    media: 'Optionale Videoplayer',
    mediaText: 'YouTube und andere zustimmungspflichtige Player erlauben. Sie erhalten Verbindungsdaten und können Cookies oder ähnliche Technologien verwenden. Diese Auswahl aktiviert A-ADS nicht.',
    standardMediaText: 'Standardvideos von Dailymotion können mit ausschließlich notwendigem Speicher verfügbar bleiben. Dailymotion erhält Verbindungsdaten und kann eigene Werbung anzeigen. Die Hinweise im Player bleiben zugänglich.',
    ads: 'A-ADS-Werbung',
    adsText: 'A-ADS-Werbung zur Unterstützung von Random erlauben. Dieser externe Dienst erhält Verbindungsdaten. Videos lassen sich separat erlauben.',
    gpc: 'Das Datenschutzsignal deines Browsers ist aktiv: A-ADS-Werbung bleibt deaktiviert.',
    blocked: 'Ein eingeschränktes Random-Erlebnis. Ohne die Erlaubnis für externe Player bleiben einige Videos gesperrt. Erlaube sie für ein vollständigeres Erlebnis.',
    allow: 'Nur Videos erlauben',
    both: 'Videos und Werbung erlauben',
    customize: 'Anpassen',
    remembered: 'Zustimmungen, auch teilweise, werden 180 Tage gespeichert, sofern der Browser dies erlaubt. Eine vollständige Ablehnung gilt für diesen Besuch; bei einem neuen Besuch fragen wir erneut. Die Auswahl lässt sich in den Datenschutzeinstellungen ändern.',
    limited: 'Videoeinstellungen',
    shortcut: 'Datenschutz',
    terms: 'Nutzungsbedingungen',
    details: 'Daten und Datenschutz',
    policy: 'Datenschutzerklärung',
  },
  es: {
    title: 'Tu experiencia Random',
    intro: 'Sin permitir los reproductores de vídeo, tu experiencia Random es limitada: algunos vídeos quedan bloqueados. Actívalos para descubrir más contenido. La publicidad de A-ADS ayuda a financiar Random y sigue siendo una elección independiente.',
    accept: 'Aceptar vídeos y publicidad',
    reject: 'Rechazar servicios opcionales',
    settings: 'Ajustes de privacidad',
    close: 'Cerrar',
    save: 'Guardar',
    necessary: 'Almacenamiento necesario',
    necessaryText: 'Idioma, preferencias, favoritos y elección de privacidad.',
    media: 'Reproductores de vídeo opcionales',
    mediaText: 'Permitir YouTube y otros reproductores que requieren autorización. Reciben datos de conexión y pueden utilizar cookies o tecnologías similares. Esta opción no activa A-ADS.',
    standardMediaText: 'Los vídeos estándar de Dailymotion pueden seguir disponibles con almacenamiento exclusivamente necesario. Dailymotion recibe datos de conexión y puede mostrar sus propios anuncios. Los avisos de su reproductor siguen accesibles.',
    ads: 'Publicidad de A-ADS',
    adsText: 'Permitir anuncios de A-ADS para apoyar a Random. Este servicio externo recibe datos de conexión. Los vídeos se pueden permitir por separado.',
    gpc: 'La señal de privacidad de tu navegador está activa: la publicidad de A-ADS permanece desactivada.',
    blocked: 'Una experiencia Random limitada. Sin permitir los reproductores externos, algunos vídeos siguen bloqueados. Actívalos para disfrutar de una experiencia más completa.',
    allow: 'Permitir solo vídeos',
    both: 'Aceptar vídeos y publicidad',
    customize: 'Personalizar',
    remembered: 'Las aceptaciones, incluidas las parciales, se guardan durante 180 días si el navegador lo permite. El rechazo total se conserva durante esta visita; volveremos a preguntar en una nueva visita. Puedes cambiarlo en los ajustes de privacidad.',
    limited: 'Ajustes de vídeo',
    shortcut: 'Privacidad',
    terms: 'Condiciones de uso',
    details: 'Datos y privacidad',
    policy: 'Política de privacidad',
  },
  jp: {
    title: 'Randomの楽しみ方',
    intro: '動画プレーヤーを許可しない場合、一部の動画がブロックされ、Randomの体験が制限されます。許可すると、さらに多くのコンテンツを発見できます。A-ADS広告はRandomの運営を支援しますが、動画とは別に選択できます。',
    accept: '動画と広告を許可',
    reject: '任意のサービスを拒否',
    settings: 'プライバシー設定',
    close: '閉じる',
    save: '保存',
    necessary: '必要な保存データ',
    necessaryText: '言語、設定、お気に入り、プライバシーの選択を保存します。',
    media: '任意の動画プレーヤー',
    mediaText: 'YouTubeなど、許可が必要なプレーヤーを読み込みます。これらのサービスは接続データを受け取り、Cookieなどを使用する場合があります。この選択ではA-ADSは有効になりません。',
    standardMediaText: 'Dailymotionの標準動画は、必要な保存データのみを使用して視聴できる場合があります。Dailymotionは接続データを受け取り、独自の広告を表示する場合があります。プレーヤー内のお知らせは引き続き確認できます。',
    ads: 'A-ADS広告',
    adsText: 'A-ADS広告を許可してRandomの運営を支援します。この外部サービスは接続データを受け取ります。動画は個別に許可できます。',
    gpc: 'ブラウザーのプライバシー信号が有効なため、A-ADS広告は無効のままです。',
    blocked: 'Randomの体験が制限されています。外部プレーヤーを許可しない場合、一部の動画はブロックされたままです。許可すると、より充実した体験を楽しめます。',
    allow: '動画のみ許可',
    both: '動画と広告を許可',
    customize: '個別に設定',
    remembered: '一部のみの許可を含め、許可の選択はブラウザーで保存できる場合に180日間記憶されます。すべて拒否した場合は今回の訪問中のみ記憶し、新たな訪問時に再び選択を表示します。プライバシー設定でいつでも変更できます。',
    limited: '動画の設定',
    shortcut: 'プライバシー',
    terms: '利用規約',
    details: 'データとプライバシー',
    policy: 'プライバシーポリシー',
  },
}
