export type CuratedWebSource = {
  url: string
  title?: string
  description?: string
  tags?: string[]
  provider?: string
  sourceName?: string
  sourceUrl?: string
}

export const CURATED_WEB_SOURCES: CuratedWebSource[] = [
  {
    url: 'https://www.thisiscolossal.com/',
    title: 'Colossal',
    description: 'Daily art, design, and visual culture discoveries.',
    tags: ['art', 'design', 'blog'],
  },
  {
    url: 'https://www.creativeapplications.net/',
    title: 'CreativeApplications.Net',
    description: 'Projects at the intersection of art, media, and technology.',
    tags: ['art', 'technology', 'interactive'],
  },
  {
    url: 'https://www.creativeboom.com/',
    title: 'Creative Boom',
    description: 'Interviews, inspiration, and resources for creative people.',
    tags: ['design', 'illustration', 'inspiration'],
  },
  {
    url: 'https://www.itsnicethat.com/',
    title: 'It’s Nice That',
    description: 'Editorial platform championing creativity across the arts.',
    tags: ['art', 'design', 'editorial'],
  },
  {
    url: 'https://www.designboom.com/',
    title: 'designboom',
    description: 'Global architecture and design magazine.',
    tags: ['design', 'architecture', 'magazine'],
  },
  {
    url: 'https://www.atlasobscura.com/',
    title: 'Atlas Obscura',
    description: 'Celebrating the world’s curious and hidden places.',
    tags: ['travel', 'culture', 'guide'],
  },
  {
    url: 'https://www.openculture.com/',
    title: 'Open Culture',
    description: 'Free cultural and educational media on the web.',
    tags: ['education', 'culture', 'media'],
  },
  {
    url: 'https://www.booooooom.com/',
    title: 'BOOOOOOOM',
    description: 'Contemporary art & photography from emerging creators.',
    tags: ['art', 'photography', 'blog'],
  },
  {
    url: 'https://www.neondystopia.com/',
    title: 'Neon Dystopia',
    description: 'Cyberpunk culture, essays, and world-building.',
    tags: ['cyberpunk', 'culture', 'fiction'],
  },
  {
    url: 'https://thecreativeindependent.com/',
    title: 'The Creative Independent',
    description: 'Interviews and resources for artists and creative workers.',
    tags: ['interviews', 'creative', 'culture'],
  },
  {
    url: 'https://stackedjournal.com/',
    title: 'Stacked Journal',
    description: 'Notebook of architecture, objects, and spatial culture.',
    tags: ['architecture', 'design'],
  },
  {
    url: 'https://www.wepresent.com/',
    title: 'WePresent',
    description: 'Stories of creativity curated by WeTransfer.',
    tags: ['stories', 'creative', 'culture'],
  },
  {
    url: 'https://www.cassettearchive.org/',
    title: 'Cassette Archive',
    description: 'Digitised cassette graphics from the 1970s to 1990s.',
    tags: ['archive', 'design', 'retro'],
  },
  {
    url: 'https://www.curiousordinary.com/',
    title: 'Curious Ordinary',
    description: 'Worldbuilding, strange histories, and miniature worlds.',
    tags: ['culture', 'storytelling'],
  },
  {
    url: 'https://www.pudding.cool/',
    title: 'The Pudding',
    description: 'Visual essays that explain ideas debated in culture.',
    tags: ['data', 'visualisation', 'culture'],
  },
  {
    url: 'https://www.ribbonfarm.com/',
    title: 'Ribbonfarm',
    description: 'Longform essays on technology, culture, and strategy.',
    tags: ['essays', 'culture', 'technology'],
  },
  {
    url: 'https://www.liamwong.com/',
    title: 'Liam Wong',
    description: 'Photography portfolio exploring neon‑soaked cityscapes.',
    tags: ['photography', 'portfolio'],
  },
  {
    url: 'https://spacewomen.club/',
    title: 'Space Women',
    description: 'Archive celebrating the women who worked on the space age.',
    tags: ['archive', 'space', 'history'],
  },
  {
    url: 'https://monoskop.org/log/',
    title: 'Monoskop Log',
    description: 'Media art, culture, and humanities research notes.',
    tags: ['media', 'art', 'research'],
  },
  {
    url: 'https://www.johnjohnston.name/106/',
    title: '#DailyCreate Archive',
    description: 'An archive of daily creative prompts from the DS106 community.',
    tags: ['creative', 'prompts', 'education'],
  },
  {
    url: 'https://www.eyecandywebsites.com/',
    title: 'EyeCandy Websites',
    description: 'Curated gallery of playful, experimental web design.',
    tags: ['design', 'gallery', 'web'],
  },
  {
    url: 'https://www.futurefonts.xyz/',
    title: 'Future Fonts',
    description: 'Marketplace of in-progress typefaces from independent foundries.',
    tags: ['typography', 'design'],
  },
  {
    url: 'https://www.cinetica.me/',
    title: 'Cinetica',
    description: 'Experiments with motion, rhythm, and interactive typography.',
    tags: ['interactive', 'design', 'motion'],
  },
  {
    url: 'https://www.shygirlworldwide.com/',
    title: 'Shygirl World',
    description: 'Hyperpop musician Shygirl’s immersive artist site.',
    tags: ['music', 'artist', 'interactive'],
  },
  {
    url: 'https://www.hvnter.com/',
    title: 'Hvnter',
    description: 'Archive of speculative stories and digital folklore.',
    tags: ['storytelling', 'speculative'],
  },
  {
    url: 'https://www.davidrumsey.com/luna/servlet',
    title: 'David Rumsey Map Collection',
    description: 'High-resolution historical maps from around the world.',
    tags: ['maps', 'archive', 'history'],
  },
  {
    url: 'https://www.peoplelovepandas.com/',
    title: 'People Love Pandas',
    description: 'A delightfully obsessive archive of panda imagery.',
    tags: ['animals', 'archive', 'niche'],
  },
  {
    url: 'https://www.cargo.site/Feature/Featured-Sites',
    title: 'Cargo Featured Sites',
    description: 'Showcase of standout Cargo portfolio websites.',
    tags: ['portfolio', 'design', 'gallery'],
  },
  {
    url: 'https://www.chromatictype.com/',
    title: 'Chromatic Type',
    description: 'Interactive collection of colour fonts and typographic experiments.',
    tags: ['typography', 'interactive'],
  },
  {
    url: 'https://longdogechallenge.com/',
    title: 'Long Doge Challenge',
    description: 'Whimsical endless scroll experiment with the long dog Doge.',
    tags: ['toy', 'experiment'],
  },
  {
    url: 'https://stars.chromeexperiments.com/',
    title: '100,000 Stars',
    description: 'Interactive visualisation of the stellar neighbourhood.',
    tags: ['space', 'interactive'],
  },
  {
    url: 'https://experiments.withgoogle.com/collection/ai',
    title: 'Google Creative Lab Experiments',
    description: 'Playful browser experiments powered by creative technology.',
    tags: ['interactive', 'technology', 'lab'],
  },
  {
    url: 'https://neal.fun/',
    title: 'Neal.fun',
    description: 'Collection of delightful, data-driven mini web experiences.',
    tags: ['toy', 'data', 'interactive'],
  },
  {
    url: 'https://experiments.mozilla.org/',
    title: 'Mozilla Experiments',
    description: 'Prototypes and experiments for the future of the open web.',
    tags: ['web', 'open-source', 'experiments'],
  },
  {
    url: 'https://www.noclip.website/',
    title: 'noclip.website',
    description: 'Explore video game worlds freely in the browser.',
    tags: ['game', 'exploration', '3d'],
  },
  {
    url: 'https://www.lowtechmagazine.com/',
    title: 'Low-Tech Magazine',
    description: 'Reflections on resilient technologies and past innovations.',
    tags: ['technology', 'sustainability'],
  },
  {
    url: 'https://solar.lowtechmagazine.com/',
    title: 'Low-Tech Magazine (Solar Edition)',
    description: 'A solar-powered, energy-aware version of Low-Tech Magazine.',
    tags: ['technology', 'web', 'sustainability'],
  },
  {
    url: 'https://www.deepskycolors.com/',
    title: 'DeepSkyColors',
    description: 'Astrophotography and colour science by Rogelio Bernal Andreo.',
    tags: ['photography', 'space'],
  },
  {
    url: 'https://www.dodgedrop.com/',
    title: 'Dodge Drop',
    description: 'A calming generative music toy built for the browser.',
    tags: ['music', 'toy', 'interactive'],
  },
  {
    url: 'https://www.collect.art/',
    title: 'Collect',
    description: 'Curated selection of contemporary art prints and editions.',
    tags: ['art', 'market'],
  },
  {
    url: 'https://www.printedweb.org/',
    title: 'Printed Web',
    description: 'Archive of network-based art and experimental publishing.',
    tags: ['art', 'archive', 'publishing'],
  },
  {
    url: 'https://www.letterformarchive.org/news',
    title: 'Letterform Archive',
    description: 'Typography, lettering, and design stories from the archive.',
    tags: ['typography', 'design', 'archive'],
  },
  {
    url: 'https://unseen-skies.com/',
    title: 'Unseen Skies',
    description: 'Interactive film companion exploring surveillance landscapes.',
    tags: ['film', 'interactive', 'culture'],
  },
  {
    url: 'https://www.frieze.com/',
    title: 'Frieze',
    description: 'Contemporary art magazine and cultural events platform.',
    tags: ['art', 'magazine'],
  },
  {
    url: 'https://www.kottke.org/',
    title: 'Kottke.org',
    description: 'Long-running blog of interesting things by Jason Kottke.',
    tags: ['blog', 'culture'],
  },
  {
    url: 'https://www.aesprite.com/',
    title: 'Aesprite Gallery',
    description: 'Community gallery of pixel art created with Aseprite.',
    tags: ['pixel art', 'gallery'],
  },
  {
    url: 'https://www.booooooomtv.com/',
    title: 'Booooooom TV',
    description: 'Curated short films, music videos, and animations.',
    tags: ['film', 'animation', 'music'],
  },
  {
    url: 'https://www.travelfish.org/',
    title: 'Travelfish',
    description: 'Independent travel guides for Southeast Asia.',
    tags: ['travel', 'guide'],
  },
  {
    url: 'https://www.ignant.com/',
    title: 'IGNANT',
    description: 'Architecture, art, design, and photography stories.',
    tags: ['design', 'architecture', 'photography'],
  },
  {
    url: 'https://www.civiclaboratory.se/',
    title: 'Civic Laboratory for Environmental Action Research',
    description: 'Community science making the ecological impacts of industry visible.',
    tags: ['science', 'environment', 'community'],
  },
  {
    url: 'https://www.papercraftsquare.com/',
    title: 'PaperCraftSquare',
    description: 'Papercraft models, templates, and DIY paper toys.',
    tags: ['craft', 'diy', 'papercraft'],
  },
  {
    url: 'https://www.postmatter.com/',
    title: 'POSTmatter',
    description: 'Digital culture magazine exploring art, design, and technology.',
    tags: ['culture', 'magazine', 'digital'],
  },
  {
    url: 'https://www.fieldkit.org/',
    title: 'Fieldkit',
    description: 'Open-source environmental sensing tools and community stories.',
    tags: ['technology', 'environment', 'open-source'],
  },
  {
    url: 'https://ambientfoc.us/',
    title: 'Ambient Focus',
    description: 'Ambient music, slow media, and contemplative tools.',
    tags: ['music', 'ambient', 'slow'],
  },
  {
    url: 'https://www.messletters.com/en/',
    title: 'Messletters',
    description: 'Playful text generator and typographic toy.',
    tags: ['toy', 'typography', 'generator'],
  },
  {
    url: 'https://www.lingscars.com/',
    title: 'Ling’s Cars',
    description: 'Infamous maximalist car leasing site packed with personality.',
    tags: ['web', 'culture', 'design'],
  },
  {
    url: 'https://www.buzzing.cc/',
    title: 'Buzzing',
    description: 'Global feed that surfaces indie newsletters and blogs.',
    tags: ['blogs', 'discovery'],
  },
  {
    url: 'https://www.flightradar24.com/',
    title: 'Flightradar24',
    description: 'Live air traffic map with detailed aircraft data.',
    tags: ['data', 'interactive', 'map'],
  },
  {
    url: 'https://www.earth.nullschool.net/',
    title: 'earth :: a global map',
    description: 'Real-time visualisation of global weather conditions.',
    tags: ['weather', 'interactive'],
  },
  {
    url: 'https://www.newyorker.com/cartoons',
    title: 'The New Yorker Cartoons',
    description: 'Daily cartoons and archive from The New Yorker.',
    tags: ['cartoons', 'magazine'],
  },
  {
    url: 'https://www.radiogarden.net/',
    title: 'Radio Garden',
    description: 'Spin the globe and listen to live radio streams worldwide.',
    tags: ['radio', 'interactive', 'map'],
  },
  {
    url: 'https://www.sounds.fm/',
    title: 'sounds.fm',
    description: 'Curated soundscapes for focus, sleep, and relaxation.',
    tags: ['music', 'ambient'],
  },
  {
    url: 'https://www.withinorwithout.com/',
    title: 'Within or Without',
    description: 'Speculative fiction and interactive essays on alternate realities.',
    tags: ['fiction', 'interactive'],
  },
  {
    url: 'https://www.folklore.org/',
    title: 'Folklore.org',
    description: 'Anecdotes about the development of Apple\'s original Macintosh.',
    tags: ['history', 'technology'],
  },
  {
    url: 'https://www.mapcrunch.com/',
    title: 'MapCrunch',
    description: 'Jump to random Google Street View locations around the world.',
    tags: ['travel', 'interactive'],
  },
  {
    url: 'https://www.paperhouses.co/',
    title: 'Paperhouses',
    description: 'Open source house plans and architectural experiments.',
    tags: ['architecture', 'open-source'],
  },
  {
    url: 'https://www.notion.so/blog',
    title: 'Notion Blog',
    description: 'Stories of workflows, creators, and product updates from Notion.',
    tags: ['productivity', 'blog'],
    provider: 'curated-list',
    sourceName: 'Notion',
    sourceUrl: 'https://www.notion.so/blog',
  },
  {
    url: 'https://www.the-sampler.net/',
    title: 'The Sampler',
    description: 'Curated newsletter bringing contemporary music projects to light.',
    tags: ['music', 'newsletter'],
  },
]
